spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
#        use_sql_comments: true
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true
    open-in-view: true
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_boot_board_example
    username: root
    password: password